### PR TITLE
Add options.params argument for non-Express environments

### PR DESCRIPTION
**Pull request by phanect**
I'm using passport from Geddy and there is no `req.body` / `req.query`. So I want an option to specify params.

### CODE REVIEW

**Comment by phanect** [comment]
@jaredhanson Can you give me help so that my test added in 7550394 runs on test?
I don't know why it doesn't run.

**Comment by phanect** [comment]
@jaredhanson

I have cut off Node.js 0.4-0.8 support in this PR.

For 0.4, NVM can't install Node.js 0.4 anymore.

For 0.8, [error occurs](https://travis-ci.org/jaredhanson/passport-local/jobs/57025012) because npm is too old. If you install the latest npm, [another error occurs](https://travis-ci.org/jaredhanson/passport-local/jobs/57028740).This issue can be solved by updating npm to 1.2, but if you do so, npm 1.2 is used even on Node.js 0.10 and 0.12. (It seems hard to use npm 1.2 only on Node 0.8.)

Is it OK? Or should I do any other work to support older Node.js versions?

**Comment by jaredhanson** [comment]
It's not consistent with the design of Passport to pass credentials into strategies.  Strategies are intended to handle parsing of requests and drive `verify` callbacks accordingly.  If you could make this PR parse requests from Geddy, I'd consider merging.

**Comment by emilong** [comment]
I'd also like to pull credentials from req.params. b46ff4c seems to do that in much the same style as the existing code does from body and query. Did I miss something in this PR that changes the design? If so, is there another approach that you would accept that uses req.params?

Thanks!

**Comment by rwky** [comment]
@phanect if you make a PR against https://github.com/passport-next/passport-local this will get looked into.

**Comment by phanect** [comment]
Apologies for leaving this PR open without any response.
Let me close this PR.

**Pull request closed without merging**
